"""
modal_backend.py — Modal cloud GPU backend for ProteinLens AI.

FIRST-TIME SETUP (run once to pre-download model weights into the volume):
    modal run modal_backend.py::setup_weights

Then deploy and keep it running:
    modal deploy modal_backend.py
"""

import modal
import os

app = modal.App("protein-lens-ai")

_PYTORCH_INDEX = "https://download.pytorch.org/whl/cu124"

# Persistent volume — SimpleFold writes its downloaded weights here.
# Without this, every cold container re-downloads and risks mid-download corruption.
# Must be a path that does NOT exist in the base image — Modal refuses to mount
# a volume over a non-empty directory.
_MODEL_CACHE = "/model-cache"
model_vol = modal.Volume.from_name("simplefold-weights", create_if_missing=True)

simplefold_image = (
    modal.Image.debian_slim(python_version="3.10")
    .apt_install("git", "wget", "curl", "build-essential", "libxrender1", "libxext6")
    .pip_install(
        "torch==2.5.1",
        "numpy>=1.26,<2",
        "biopython==1.85",
        "requests",
        extra_options=f"--extra-index-url {_PYTORCH_INDEX}",
    )
    .run_commands(
        "pip install 'git+https://github.com/apple/ml-simplefold.git'",
        "pip install 'git+https://github.com/facebookresearch/esm.git'",
        "simplefold --help",
    )
    .env({"HF_HOME": _MODEL_CACHE, "TORCH_HOME": _MODEL_CACHE})
)


# ── One-time weight download ───────────────────────────────────────────────────

@app.function(
    image=simplefold_image,
    gpu="T4",
    timeout=1800,           # 30 min — enough for a full model download
    volumes={_MODEL_CACHE: model_vol},
)
def setup_weights(model: str = "simplefold_100M"):
    """
    Run SimpleFold on a tiny sequence to trigger weight download into the volume.
    Run this ONCE before your first inference call:

        modal run modal_backend.py::setup_weights
    """
    import subprocess, tempfile, os

    print(f"Downloading {model} weights into volume...")

    with tempfile.TemporaryDirectory() as tmpdir:
        fasta_path = os.path.join(tmpdir, "input.fasta")
        with open(fasta_path, "w") as f:
            f.write(">warmup\nACDEFGHIKLMNPQRSTVWY\n")   # 20-AA test sequence

        output_dir = os.path.join(tmpdir, "out")
        os.makedirs(output_dir)

        result = subprocess.run(
            [
                "simplefold",
                "--simplefold_model", model,
                "--num_steps", "10",           # minimum steps — we only need the download
                "--fasta_path", fasta_path,
                "--output_dir", output_dir,
                "--backend", "torch",
            ],
            capture_output=True,
            text=True,
            timeout=1700,
        )

    if result.returncode == 0:
        print(f"✓ Weights for {model} downloaded and cached in volume.")
    else:
        print(f"✗ Download failed (exit {result.returncode}).")
        print(result.stderr[-1000:])
        raise RuntimeError("Weight download failed — see stderr above.")

    # Flush volume so weights persist immediately
    model_vol.commit()


# ── Inference function ─────────────────────────────────────────────────────────

@app.function(
    image=simplefold_image,
    gpu="T4",
    timeout=600,
    retries=1,
    memory=8192,
    volumes={_MODEL_CACHE: model_vol},
)
def fold_protein_modal(
    sequence: str,
    model: str = "simplefold_100M",
    num_steps: int = 500,
) -> dict:
    import subprocess, tempfile, os

    with tempfile.TemporaryDirectory() as tmpdir:
        fasta_path = os.path.join(tmpdir, "input.fasta")
        with open(fasta_path, "w") as f:
            f.write(f">protein\n{sequence}\n")

        output_dir = os.path.join(tmpdir, "output")
        os.makedirs(output_dir)

        result = subprocess.run(
            [
                "simplefold",
                "--simplefold_model", model,
                "--num_steps", str(num_steps),
                "--tau", "0.01",
                "--nsample_per_protein", "1",
                "--plddt",
                "--fasta_path", fasta_path,
                "--output_dir", output_dir,
                "--backend", "torch",
            ],
            capture_output=True,
            text=True,
            timeout=540,
        )

        if result.returncode != 0:
            raise RuntimeError(
                f"SimpleFold error (code {result.returncode}):\n{result.stderr[-800:]}"
            )

        pdb_string = None
        for root, _, files in os.walk(output_dir):
            for fname in files:
                if fname.endswith(".pdb"):
                    with open(os.path.join(root, fname)) as pf:
                        pdb_string = pf.read()
                    break

        if pdb_string is None:
            raise FileNotFoundError("No PDB file generated by SimpleFold.")

        scores = []
        for line in pdb_string.splitlines():
            if line.startswith(("ATOM", "HETATM")):
                try:
                    scores.append(float(line[60:66].strip()))
                except (ValueError, IndexError):
                    pass
        confidence = (sum(scores) / len(scores) / 100.0) if scores else 0.75

        return {"pdb_string": pdb_string, "confidence": confidence, "model": model}


# ── Convenience wrapper ────────────────────────────────────────────────────────

def fold_on_modal(
    sequence: str,
    model: str = "simplefold_100M",
    num_steps: int = 500,
) -> tuple[str, float]:
    result = fold_protein_modal.remote(sequence, model=model, num_steps=num_steps)
    return result["pdb_string"], result["confidence"]


# ── Local smoke test ───────────────────────────────────────────────────────────

@app.local_entrypoint()
def test():
    test_seq = "ACDEFGHIKLMNPQRSTVWY"
    print(f"Testing Modal fold ({len(test_seq)} AA)...")
    result = fold_protein_modal.remote(test_seq, model="simplefold_100M", num_steps=100)
    print(f"Confidence: {result['confidence']:.1%}  |  PDB lines: {len(result['pdb_string'].splitlines())}")
