"""
modal_backend.py — Optional Modal cloud GPU backend for ProteinLens AI.

Deploys SimpleFold as a serverless GPU function on Modal.
Use this when you want cloud-scale inference (larger models, no local GPU needed).

Deploy:
    modal deploy modal_backend.py

Call from app:
    from modal_backend import fold_on_modal
    pdb, confidence = fold_on_modal(sequence, model="simplefold_700M")

Requirements:
    pip install modal
    modal token new   # authenticate via browser
"""

import modal
import os

# ── Modal app definition ───────────────────────────────────────────────────────
app = modal.App("protein-lens-ai")

# Docker image: install SimpleFold with PyTorch (cloud GPU = CUDA, not MLX)
simplefold_image = (
    modal.Image.debian_slim(python_version="3.10")
    .apt_install("git", "wget", "curl")
    .pip_install(
        "torch>=2.0.0",
        "numpy",
        "biopython",
        "requests",
    )
    .run_commands(
        # Install SimpleFold directly from GitHub
        "pip install git+https://github.com/apple/ml-simplefold.git",
        # Install ESM dependency for tokenization
        "pip install git+https://github.com/facebookresearch/esm.git",
    )
)


# ── Modal serverless function ──────────────────────────────────────────────────

@app.function(
    image=simplefold_image,
    gpu="T4",                # T4 is cheapest; swap to "A10G" for 360M+ models
    timeout=600,             # 10-minute hard timeout
    retries=1,
    memory=8192,
)
def fold_protein_modal(
    sequence: str,
    model: str = "simplefold_100M",
    num_steps: int = 500,
) -> dict:
    """
    GPU-accelerated protein folding via SimpleFold on Modal cloud.

    Args:
        sequence:  Amino acid sequence (uppercase, single-letter codes).
        model:     SimpleFold model variant.
        num_steps: Inference steps.

    Returns:
        Dict with keys: pdb_string (str), confidence (float), model (str).
    """
    import subprocess
    import tempfile
    import os

    with tempfile.TemporaryDirectory() as tmpdir:
        # Write FASTA
        fasta_path = os.path.join(tmpdir, "input.fasta")
        with open(fasta_path, "w") as f:
            f.write(f">protein\n{sequence}\n")

        output_dir = os.path.join(tmpdir, "output")
        os.makedirs(output_dir)

        cmd = [
            "simplefold",
            "--simplefold_model", model,
            "--num_steps", str(num_steps),
            "--tau", "0.01",
            "--nsample_per_protein", "1",
            "--plddt",
            "--fasta_path", fasta_path,
            "--output_dir", output_dir,
            "--backend", "torch",     # CUDA backend on Modal GPU
        ]

        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=540,
        )

        if result.returncode != 0:
            raise RuntimeError(
                f"SimpleFold error (code {result.returncode}):\n{result.stderr[-800:]}"
            )

        # Find PDB output
        pdb_string = None
        for root, _, files in os.walk(output_dir):
            for fname in files:
                if fname.endswith(".pdb"):
                    with open(os.path.join(root, fname)) as pf:
                        pdb_string = pf.read()
                    break

        if pdb_string is None:
            raise FileNotFoundError("No PDB file generated by SimpleFold.")

        # Extract mean pLDDT
        scores = []
        for line in pdb_string.splitlines():
            if line.startswith(("ATOM", "HETATM")):
                try:
                    scores.append(float(line[60:66].strip()))
                except (ValueError, IndexError):
                    pass
        confidence = (sum(scores) / len(scores) / 100.0) if scores else 0.75

        return {"pdb_string": pdb_string, "confidence": confidence, "model": model}


# ── Convenience wrapper for local Streamlit app ───────────────────────────────

def fold_on_modal(
    sequence: str,
    model: str = "simplefold_100M",
    num_steps: int = 500,
) -> tuple[str, float]:
    """
    Call the Modal cloud function from your local Streamlit app.

    Requires `modal token new` to have been run once for authentication.

    Returns:
        (pdb_string, confidence)
    """
    result = fold_protein_modal.remote(sequence, model=model, num_steps=num_steps)
    return result["pdb_string"], result["confidence"]


# ── Local test entrypoint ──────────────────────────────────────────────────────

@app.local_entrypoint()
def test():
    """Quick smoke test: fold a tiny peptide."""
    test_seq = "ACDEFGHIKLMNPQRSTVWY"  # 20 AA — one of each amino acid
    print(f"Testing Modal fold with sequence length {len(test_seq)}...")
    result = fold_protein_modal.remote(test_seq, model="simplefold_100M", num_steps=100)
    print(f"Success! Confidence: {result['confidence']:.1%}")
    print(f"PDB lines: {len(result['pdb_string'].splitlines())}")
